name = "PortfolioOptim"
uuid = "2d76e5c4-dedf-40d5-b75c-d66db368753d"
authors = ["Harry LaBollita"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
