name: CI
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
    test:
      name : tests
      runs-on: ubuntu-latest
      strategy:
        matrix:
          group:
            - All
          julia-version:
            - '1.7'
          python-version:
            - '3.9'
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: ${{matrix.python-version}}

        - name: install scipy
          run: pip install scipy

        - uses: julia-actions/setup-julia@v1
          with:
            version: ${{matrix.julia-version }}

        - uses: julia-actions/julia-buildpkg@v1
        - uses: julia-actions/julia-runtest@v1
