name: CI
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
    test:
      name : tests
      runs-on: ubuntu-latest
      strategy:
        matrix:
          group:
            - All
          version:
            - '1.7'
      steps:
        - uses: actions/checkout@v2
        - uses: julia-actions/setup-julia@v1
          with:
            version: ${{matrix.version }}
        - uses: julia-actions/julia-buildpkg@v1
        - uses: julia-actions/julia-runtest@v1
