name: CI
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
    test:
      name : tests
      runs-on: ubuntu-latest
      strategy:
        matrix:
          group:
            - All
          version:
            - '1.7'
      steps:
        - uses: actions/checkout@v2
        - uses: julia-actions/setup-julia@v1
          with:
            version: ${{matrix.version }}
        - name: Install Conda dependencies
          shell: bash
          run: |
            julia -e '
              using Pkg; Pkg.add("Conda"); using Conda
              pkgs  = ["scipy"]
              Conda.add(pkgs; channel="conda-forge")
              '
        - uses: julia-actions/julia-buildpkg@v1
        - uses: julia-actions/julia-runtest@v1
